const PUERTO = 8080;

const METODO_EFECTIVO = "EFECTIVO";
const METODO_TARJETA_CREDITO = "TARJETA";
const METODOS_FORMA_PAGO = {METODO_EFECTIVO, METODO_TARJETA_CREDITO}

const MODELO_CIUDADES = "Ciudades";
const MODELO_PEDIDO = "PedidosLoQueSea";
const MODELO_USUARIOS = "Usuarios"
const MODELOS_BD = {MODELO_CIUDADES, MODELO_PEDIDO, MODELO_USUARIOS}


const CONSTANTES = {
    PUERTO,
    METODOS_FORMA_PAGO,
    MODELOS_BD
};

export default CONSTANTES;
